stages:
  clean_pretraining_data:
    cmd: python src/clean_pretraining_data.py --config=params.yaml
    deps:
      - src/clean_pretraining_data.py
      - data/raw/summary/train.src.txt
    params:
      - data.summarization_full_txt
      - data.pretraining_txt
    outs:
      - data/raw/pretraining/pretraining.txt

  create_pretraining_split:
    cmd: python src/create_pretraining_split.py --config=params.yaml
    deps:
      - src/create_pretraining_split.py
      - data/raw/pretraining/pretraining.txt
    params:
      - data.pretraining_txt
      - data.pretraining_train
      - data.pretraining_val
    outs:
      - data/raw/pretraining/pretraining_train.pkl
      - data/raw/pretraining/pretraining_val.pkl

  training_pretraining:
    cmd: python src/training.py --config=params.yaml
    deps:
      - src/training.py
      - data/raw/pretraining/pretraining_train.pkl
      - data/raw/pretraining/pretraining_val.pkl
    params:
      - hyperparameters.vocab_size
      - hyperparameters.n_embd
      - hyperparameters.block_size
      - hyperparameters.n_head
      - hyperparameters.n_layer
      - hyperparameters.dropout
      - hyperparameters.batch_size
      - hyperparameters.learning_rate
      - hyperparameters.max_iters
      - hyperparameters.eval_iters
      - hyperparameters.eval_interval
      - data.pretraining_train
      - data.pretraining_val
      - mlflow_pretraining.server_uri
      - mlflow_pretraining.experiment_name
      - mlflow_pretraining.run_name
      - mlflow_pretraining.registered_model_name
    outs:
      - training_completion.txt

  log_pretraining_model:
    cmd: python src/log_pretraining_model.py --config=params.yaml
    deps:
      - src/log_pretraining_model.py
      - training_completion.txt
    params:
      - mlflow_pretraining.server_uri
      - mlflow_pretraining.experiment_name
    outs:
      - saved_models/pretrained.pth

  create_summary_data:
    cmd: python src/create_summary_data.py --config=params.yaml
    deps:
      - src/create_summary_data.py
      - data/raw/summary/train.src.txt
      - data/raw/summary/train.tgt.txt
    params:
      - data.summarization_full_txt
      - data.summarization_summary_txt
      - hyperparameters.block_size
      - data.vocab_dir
    outs:
      - data/raw/summary/filtered.parquet

  create_summary_split:
    cmd: python src/create_summary_split.py --config=params.yaml
    deps:
      - src/create_summary_split.py
      - data/raw/summary/filtered.parquet
    params:
      - data.summarization_filtered_parquet
      - data.train_full
      - data.train_summary
      - data.val_full
      - data.val_summary
    outs:
      - data/raw/summary/train_full.pkl
      - data/raw/summary/train_summary.pkl
      - data/raw/summary/val_full.pkl
      - data/raw/summary/val_summary.pkl

  summary_training:
    cmd: python src/summary_training.py --config=params.yaml
    deps:
      - src/summary_training.py
      - data/raw/summary/train_full.pkl
      - data/raw/summary/train_summary.pkl
      - data/raw/summary/val_full.pkl
      - data/raw/summary/val_summary.pkl
      - saved_models/pretrained.pth
      - training_completion.txt
    params:
      - log_pretrained_model.model_dir
      - summary_hyperparameters.learning_rate
      - summary_hyperparameters.max_iters
      - summary_hyperparameters.batch_size
      - hyperparameters.eval_interval
      - hyperparameters.block_size
      - hyperparameters.eval_iters
      - data.train_full
      - data.train_summary
      - data.val_full
      - data.val_summary
      - mlflow_summary.experiment_name
      - mlflow_summary.run_name
      - mlflow_summary.registered_model_name
      - mlflow_summary.server_uri
    outs:
      - training_summary_completion.txt

  log_summary_model:
    cmd: python src/log_summary_model.py --config=params.yaml
    deps:
      - src/log_summary_model.py
      - training_summary_completion.txt
    params:
      - mlflow_summary.server_uri
      - mlflow_summary.experiment_name
    outs:
      - saved_models/summary.pth
