stages:
  create_pretraining_data:
    cmd: python src/create_pretraining_data.py --config=params.yaml
    deps:
      - src/create_pretraining_data.py
    params:
      - data.pretraining_parquet
      - data.pretraining_txt
    outs:
      - data/raw/pretraining/pretraining.txt

  create_tokenizer:
    cmd: python src/create_tokenizer.py --config=params.yaml
    deps:
      - src/create_tokenizer.py
      - data/raw/pretraining/pretraining.txt
    params:
      - data.pretraining_txt
      - data.vocab_dir
      - hyperparameters.vocab_size
    outs:
      - data/tokenizer/spm_model.model

  create_pretraining_split:
    cmd: python src/create_pretraining_split.py --config=params.yaml
    deps:
      - src/create_pretraining_split.py
      - data/raw/pretraining/pretraining.txt
      - data/tokenizer/spm_model.model
    params:
      - data.pretraining_txt
      - data.pretraining_train
      - data.pretraining_val
      - data.vocab_dir
    outs:
      - data/raw/pretraining/pretraining_train.pkl
      - data/raw/pretraining/pretraining_val.pkl

  training_pretraining:
    cmd: python src/training.py --config=params.yaml
    deps:
      - src/training.py
      - data/raw/pretraining/pretraining_train.pkl
      - data/raw/pretraining/pretraining_val.pkl
    params:
      - hyperparameters.vocab_size
      - hyperparameters.n_embd
      - hyperparameters.block_size
      - hyperparameters.n_head
      - hyperparameters.n_layer
      - hyperparameters.dropout
      - hyperparameters.batch_size
      - hyperparameters.learning_rate
      - hyperparameters.max_iters
      - hyperparameters.eval_iters
      - hyperparameters.eval_interval
      - data.pretraining_train
      - data.pretraining_val
      - mlflow_pretraining.server_uri
      - mlflow_pretraining.experiment_name
      - mlflow_pretraining.run_name
      - mlflow_pretraining.registered_model_name
    outs:
      - training_completion.txt

  log_pretraining_model:
    cmd: python src/log_pretraining_model.py --config=params.yaml
    deps:
      - src/log_pretraining_model.py
      - training_completion.txt
    params:
      - mlflow_pretraining.server_uri
      - mlflow_pretraining.experiment_name
    outs:
      - saved_models/pretrained.pth

  create_summary_data:
    cmd: python src/create_summary_data.py --config=params.yaml
    deps:
      - src/create_summary_data.py
      - data/raw/summary/train-00000-of-00002.parquet
    params:
      - data.summarization_parquet
      - hyperparameters.block_size
      - data.vocab_dir
    outs:
      - data/raw/summary/filtered.parquet
