data:
  pretraining_txt: data/raw/pretraining/pretraining.txt
  pretraining_train: data/raw/pretraining/pretraining_train.pkl
  pretraining_val: data/raw/pretraining/pretraining_val.pkl
  summarization_full_txt: data/raw/summary/train.src.txt
  summarization_summary_txt: data/raw/summary/train.tgt.txt
  summarization_filtered_parquet: data/raw/summary/filtered.parquet
  train_full: data/raw/summary/train_full.pkl
  train_summary: data/raw/summary/train_summary.pkl
  val_full: data/raw/summary/val_full.pkl
  val_summary: data/raw/summary/val_summary.pkl

hyperparameters:
  vocab_size: 50260
  n_embd: 768
  block_size: 128
  n_head: 12
  n_layer: 12
  dropout: 0.2
  learning_rate: 2e-4
  epochs: 3
  max_iters: 2500
  batch_size: 256
  mini_batch_size: 16
  eval_iters: 50
  eval_interval: 500

mlflow_pretraining:
  server_uri: sqlite:///mlflow.db
  experiment_name: Pretraining
  run_name: 1st
  registered_model_name: Pretrained GPT

mlflow_summary:
  server_uri: sqlite:///mlflow.db
  experiment_name: Summary
  run_name: 1st
  registered_model_name: Summary GPT

log_pretrained_model:
  model_dir: saved_models/pretrained.pth

log_summary_model:
  model_dir: saved_models/summary.pth

summary_hyperparameters:
  learning_rate: 5e-5
  epochs: 1
  max_iters: 20000
  batch_size: 32
  mini_batch_size: 16
  eval_interval: 500
  eval_iters: 50
